version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - mvn compile
  post_build:
    commands:
      - mvn package
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.war
